ALTER TABLE FTIAPP.STUDENT_PRE_ENROLLMENT ADD (
    STATUS VARCHAR2(30) DEFAULT 'PARAREGJISTRUAR' NOT NULL
);

UPDATE FTIAPP.STUDENT_PRE_ENROLLMENT pe
SET pe.STATUS = 'VERIFIKUAR'
WHERE LOWER(pe.EMAIL) IN (SELECT LOWER(u.EMAIL) FROM FTIAPP.USERS u WHERE u.VERIFIED = 'Y');
