UPDATE FTIAPP.PROFESSORS
SET USER_ID = (
    SELECT USER_ID 
    FROM FTIAPP.USERS 
    WHERE LOWER(EMAIL) LIKE '%altea%' OR LOWER(EMRI) LIKE '%altea%'
    FETCH FIRST 1 ROWS ONLY
)
WHERE PROFESSOR_ID = 26
AND (USER_ID IS NULL OR USER_ID != (
    SELECT USER_ID 
    FROM FTIAPP.USERS 
    WHERE LOWER(EMAIL) LIKE '%altea%' OR LOWER(EMRI) LIKE '%altea%'
    FETCH FIRST 1 ROWS ONLY
));
