MERGE INTO FTIAPP.COURSE_TYPES target
USING (
    SELECT 'LEKSION' AS EMRI_TYPE FROM DUAL UNION ALL
    SELECT 'SEMINAR' AS EMRI_TYPE FROM DUAL UNION ALL
    SELECT 'LABORATOR' AS EMRI_TYPE FROM DUAL
) src
ON (LOWER(target.EMRI_TYPE) = LOWER(src.EMRI_TYPE))
WHEN NOT MATCHED THEN
    INSERT (EMRI_TYPE) VALUES (src.EMRI_TYPE);

MERGE INTO FTIAPP.ROOMS target
USING (
    SELECT 'Salla 101' AS ROOM_NAME, 50 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 102' AS ROOM_NAME, 50 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 201' AS ROOM_NAME, 60 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 202' AS ROOM_NAME, 60 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 203' AS ROOM_NAME, 50 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 204' AS ROOM_NAME, 50 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 205' AS ROOM_NAME, 70 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 301' AS ROOM_NAME, 45 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 302' AS ROOM_NAME, 45 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 303' AS ROOM_NAME, 45 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Salla 304' AS ROOM_NAME, 45 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Amfiteatri A1' AS ROOM_NAME, 150 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Amfiteatri A2' AS ROOM_NAME, 150 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Lab 1' AS ROOM_NAME, 30 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Lab 2' AS ROOM_NAME, 30 AS CAPACITY FROM DUAL UNION ALL
    SELECT 'Lab 3' AS ROOM_NAME, 30 AS CAPACITY FROM DUAL
) src
ON (LOWER(target.ROOM_NAME) = LOWER(src.ROOM_NAME))
WHEN NOT MATCHED THEN
    INSERT (ROOM_NAME, CAPACITY) VALUES (src.ROOM_NAME, src.CAPACITY);
