ALTER TABLE FTIAPP.COURSE_SCHEDULE ADD (
    START_TIME_STR VARCHAR2(10),
    END_TIME_STR   VARCHAR2(10)
);

UPDATE FTIAPP.COURSE_SCHEDULE 
SET START_TIME_STR = TO_CHAR(START_TIME, 'HH24:MI'),
    END_TIME_STR   = TO_CHAR(END_TIME, 'HH24:MI');

ALTER TABLE FTIAPP.COURSE_SCHEDULE DROP (START_TIME, END_TIME);

ALTER TABLE FTIAPP.COURSE_SCHEDULE RENAME COLUMN START_TIME_STR TO START_TIME;
ALTER TABLE FTIAPP.COURSE_SCHEDULE RENAME COLUMN END_TIME_STR TO END_TIME;

ALTER TABLE FTIAPP.COURSE_SCHEDULE MODIFY (
    START_TIME VARCHAR2(10) NOT NULL,
    END_TIME   VARCHAR2(10) NOT NULL
);
