CREATE TABLE FTIAPP.USERS (
    USER_ID   INTEGER DEFAULT "FTIAPP"."ISEQ$$_99229".nextval NOT NULL,
    EMRI      VARCHAR2(50),
    MBIEMRI   VARCHAR2(50),
    EMAIL     VARCHAR2(50),
    PASSWORD  VARCHAR2(50),
    CREATED_AT DATE DEFAULT sysdate,
    STATUS    VARCHAR2(50),
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);

CREATE TABLE FTIAPP.ROLES (
    ROLE_ID   NUMBER DEFAULT "FTIAPP"."ISEQ$$_99344".nextval NOT NULL,
    ROLE_NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT SYS_C008608 PRIMARY KEY (ROLE_ID),
    CONSTRAINT SYS_C008609 UNIQUE (ROLE_NAME)
);

CREATE TABLE FTIAPP.USER_ROLES (
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    CONSTRAINT SYS_C008612 PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT SYS_C008613 FOREIGN KEY (USER_ID) REFERENCES FTIAPP.USERS(USER_ID),
    CONSTRAINT SYS_C008614 FOREIGN KEY (ROLE_ID) REFERENCES FTIAPP.ROLES(ROLE_ID)
);

CREATE TABLE FTIAPP.DEPARTMENTS (
    DEPARTMENT_ID     INTEGER DEFAULT "FTIAPP"."ISEQ$$_99250".nextval NOT NULL,
    EMER_DEPARTAMENTI VARCHAR2(100),
    HEAD_USER_ID      INTEGER,
    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT UQ_DEPARTMENT_HEAD UNIQUE (HEAD_USER_ID),
    CONSTRAINT FK_DEPARTMENTS_HEAD FOREIGN KEY (HEAD_USER_ID) REFERENCES FTIAPP.USERS(USER_ID)
);

CREATE TABLE FTIAPP.PROGRAMS (
    PROGRAM_ID    INTEGER DEFAULT "FTIAPP"."ISEQ$$_99256".nextval NOT NULL,
    DEPARTMENT_ID NUMBER,
    NIVEL         VARCHAR2(20) NOT NULL,
    LLOJI         VARCHAR2(20) NOT NULL,
    SPECIALIZIMI  VARCHAR2(100) NOT NULL,
    CONSTRAINT SYS_C008562 PRIMARY KEY (PROGRAM_ID),
    CONSTRAINT SYS_C008563 FOREIGN KEY (DEPARTMENT_ID) REFERENCES FTIAPP.DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE FTIAPP.PROFESSORS (
    PROFESSOR_ID  INTEGER DEFAULT "FTIAPP"."ISEQ$$_99235".nextval NOT NULL,
    USER_ID       INTEGER,
    STATUS        CHAR(1),
    DEPARTMENT_ID INTEGER,
    CONSTRAINT PK_PROFESSORS PRIMARY KEY (PROFESSOR_ID),
    CONSTRAINT FK_PROFESSORS_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID) REFERENCES FTIAPP.DEPARTMENTS(DEPARTMENT_ID),
    CONSTRAINT FK_PROFESSORS_USERS FOREIGN KEY (USER_ID) REFERENCES FTIAPP.USERS(USER_ID)
);

CREATE TABLE FTIAPP.CLASSES (
    CLASS_ID     INTEGER DEFAULT "FTIAPP"."ISEQ$$_99269".nextval NOT NULL,
    PROGRAM_ID   NUMBER NOT NULL,
    VIT_STUDIMIT NUMBER NOT NULL,
    EMRI_CLASS   VARCHAR2(50) NOT NULL,
    CONSTRAINT SYS_C008591 PRIMARY KEY (CLASS_ID),
    CONSTRAINT SYS_C008592 FOREIGN KEY (PROGRAM_ID) REFERENCES FTIAPP.PROGRAMS(PROGRAM_ID)
);

CREATE TABLE FTIAPP.STUDENTS (
    STUDENT_ID    INTEGER DEFAULT "FTIAPP"."ISEQ$$_99259".nextval NOT NULL,
    USER_ID       NUMBER NOT NULL,
    PROGRAM_ID    NUMBER NOT NULL,
    VIT_STUDIMIT  NUMBER NOT NULL,
    STATUS        VARCHAR2(50),
    TOTAL_KREDITE NUMBER,
    DEPARTMENT_ID INTEGER,
    CLASS_ID      INTEGER,
    CONSTRAINT SYS_C008568 PRIMARY KEY (STUDENT_ID),
    CONSTRAINT SYS_C008569 FOREIGN KEY (USER_ID) REFERENCES FTIAPP.USERS(USER_ID),
    CONSTRAINT SYS_C008570 FOREIGN KEY (PROGRAM_ID) REFERENCES FTIAPP.PROGRAMS(PROGRAM_ID),
    CONSTRAINT FK_STUDENTS_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID) REFERENCES FTIAPP.DEPARTMENTS(DEPARTMENT_ID),
    CONSTRAINT FK_STUDENTS_CLASSES FOREIGN KEY (CLASS_ID) REFERENCES FTIAPP.CLASSES(CLASS_ID)
);

CREATE TABLE FTIAPP.COURSE_TYPES (
    TYPE_ID   NUMBER DEFAULT "FTIAPP"."ISEQ$$_99265".nextval NOT NULL,
    EMRI_TYPE VARCHAR2(50) NOT NULL,
    CONSTRAINT SYS_C008585 PRIMARY KEY (TYPE_ID),
    CONSTRAINT SYS_C008586 UNIQUE (EMRI_TYPE)
);

CREATE TABLE FTIAPP.COURSES (
    COURSE_ID    INTEGER DEFAULT "FTIAPP"."ISEQ$$_99238".nextval NOT NULL,
    PROGRAM_ID   INTEGER,
    EMRI_COURSE  VARCHAR2(50) NOT NULL,
    KREDITE      INTEGER NOT NULL,
    STATUS       VARCHAR2(50),
    CONSTRAINT PK_COURSES PRIMARY KEY (COURSE_ID),
    CONSTRAINT FK_COURSES_PROGRAMS FOREIGN KEY (PROGRAM_ID) REFERENCES FTIAPP.PROGRAMS(PROGRAM_ID)
);

CREATE TABLE FTIAPP.COURSE_DEPARTMENTS (
    COURSE_ID     NUMBER NOT NULL,
    DEPARTMENT_ID NUMBER NOT NULL,
    CONSTRAINT PK_COURSE_DEPARTMENTS PRIMARY KEY (COURSE_ID, DEPARTMENT_ID),
    CONSTRAINT SYS_C008642 FOREIGN KEY (COURSE_ID) REFERENCES FTIAPP.COURSES(COURSE_ID),
    CONSTRAINT SYS_C008643 FOREIGN KEY (DEPARTMENT_ID) REFERENCES FTIAPP.DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE FTIAPP.COURSE_COURSETYPES (
    COURSE_ID NUMBER NOT NULL,
    TYPE_ID   NUMBER NOT NULL,
    CONSTRAINT SYS_C008600 PRIMARY KEY (COURSE_ID, TYPE_ID),
    CONSTRAINT SYS_C008601 FOREIGN KEY (COURSE_ID) REFERENCES FTIAPP.COURSES(COURSE_ID),
    CONSTRAINT SYS_C008602 FOREIGN KEY (TYPE_ID) REFERENCES FTIAPP.COURSE_TYPES(TYPE_ID)
);

CREATE TABLE FTIAPP.TEACHING_COURSES (
    TEACHING_COURSE_ID NUMBER DEFAULT "FTIAPP"."ISEQ$$_99443".nextval NOT NULL,
    COURSE_ID          NUMBER NOT NULL,
    PROFESSOR_ID       NUMBER NOT NULL,
    YEAR               NUMBER NOT NULL,
    SEMESTER           VARCHAR2(10),
    DURATION_WEEKS     NUMBER,
    CONSTRAINT SYS_C008648 PRIMARY KEY (TEACHING_COURSE_ID),
    CONSTRAINT SYS_C008649 FOREIGN KEY (COURSE_ID) REFERENCES FTIAPP.COURSES(COURSE_ID),
    CONSTRAINT SYS_C008650 FOREIGN KEY (PROFESSOR_ID) REFERENCES FTIAPP.PROFESSORS(PROFESSOR_ID)
);

CREATE TABLE FTIAPP.TEACHING_COURSES_CLASSES (
    TEACHING_COURSE_ID NUMBER NOT NULL,
    CLASS_ID           NUMBER NOT NULL,
    CONSTRAINT SYS_C008653 PRIMARY KEY (TEACHING_COURSE_ID, CLASS_ID),
    CONSTRAINT SYS_C008654 FOREIGN KEY (TEACHING_COURSE_ID) REFERENCES FTIAPP.TEACHING_COURSES(TEACHING_COURSE_ID),
    CONSTRAINT SYS_C008655 FOREIGN KEY (CLASS_ID) REFERENCES FTIAPP.CLASSES(CLASS_ID)
);

CREATE TABLE FTIAPP.TOPICS (
    TOPIC_ID           NUMBER DEFAULT "FTIAPP"."ISEQ$$_99448".nextval NOT NULL,
    TITLE              VARCHAR2(100) NOT NULL,
    DESCRIPTION        VARCHAR2(500),
    WEEK_NUMBER        NUMBER,
    TEACHING_COURSE_ID NUMBER,
    CONSTRAINT SYS_C008659 PRIMARY KEY (TOPIC_ID),
    CONSTRAINT SYS_C008661 FOREIGN KEY (TEACHING_COURSE_ID) REFERENCES FTIAPP.TEACHING_COURSES(TEACHING_COURSE_ID)
);

CREATE TABLE FTIAPP.GRADES (
    GRADE_ID           NUMBER DEFAULT "FTIAPP"."ISEQ$$_99357".nextval NOT NULL,
    STUDENT_ID         NUMBER NOT NULL,
    GRADE              NUMBER(3,1),
    STATUS             VARCHAR2(20),
    DATE_GIVEN         DATE DEFAULT SYSDATE,
    TEACHING_COURSE_ID NUMBER,
    CONSTRAINT SYS_C008634 PRIMARY KEY (GRADE_ID),
    CONSTRAINT UQ_STUDENT_COURSE UNIQUE (STUDENT_ID, TEACHING_COURSE_ID),
    CONSTRAINT SYS_C008635 FOREIGN KEY (STUDENT_ID) REFERENCES FTIAPP.STUDENTS(STUDENT_ID),
    CONSTRAINT FK_GRADES_TEACHING_COURSES FOREIGN KEY (TEACHING_COURSE_ID) REFERENCES FTIAPP.TEACHING_COURSES(TEACHING_COURSE_ID)
);

CREATE TABLE FTIAPP.ATTENDANCE (
    ATTENDANCE_ID      INTEGER DEFAULT "FTIAPP"."ISEQ$$_99262".nextval NOT NULL,
    STUDENT_ID         NUMBER NOT NULL,
    TEACHING_COURSE_ID INTEGER NOT NULL,
    DATA_ATTENDANCE    DATE NOT NULL,
    STATUS             NUMBER(1) DEFAULT 1,
    CONSTRAINT SYS_C008577 PRIMARY KEY (ATTENDANCE_ID),
    CONSTRAINT SYS_C008576 CHECK (status IN (0,1)),
    CONSTRAINT SYS_C008578 FOREIGN KEY (STUDENT_ID) REFERENCES FTIAPP.STUDENTS(STUDENT_ID),
    CONSTRAINT A FOREIGN KEY (TEACHING_COURSE_ID) REFERENCES FTIAPP.TEACHING_COURSES(TEACHING_COURSE_ID)
);

CREATE TABLE FTIAPP.FAILED_COURSES (
    FAILED_ID          NUMBER DEFAULT "FTIAPP"."ISEQ$$_99454".nextval NOT NULL,
    STUDENT_ID         NUMBER NOT NULL,
    TEACHING_COURSE_ID NUMBER NOT NULL,
    STATUS             VARCHAR2(50) DEFAULT 'FREKUENTIM',
    DATE_RECORDED      DATE DEFAULT SYSDATE,
    CONSTRAINT SYS_C008675 PRIMARY KEY (FAILED_ID),
    CONSTRAINT FK_FAILED_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES FTIAPP.STUDENTS(STUDENT_ID),
    CONSTRAINT FK_FAILED_TEACHING_COURSE FOREIGN KEY (TEACHING_COURSE_ID) REFERENCES FTIAPP.TEACHING_COURSES(TEACHING_COURSE_ID)
);

CREATE TABLE FTIAPP.ROOMS (
    ROOM_ID   NUMBER DEFAULT "FTIAPP"."ISEQ$$_99547".nextval NOT NULL,
    ROOM_NAME VARCHAR2(50),
    CAPACITY  NUMBER,
    CONSTRAINT SYS_C008699 PRIMARY KEY (ROOM_ID)
);

CREATE TABLE FTIAPP.EXAMS_SCHEDULE (
    EXAM_ID      NUMBER DEFAULT "FTIAPP"."ISEQ$$_99550".nextval NOT NULL,
    COURSE_ID    NUMBER NOT NULL,
    PROGRAM_ID   NUMBER NOT NULL,
    EXAM_DATE    TIMESTAMP(6) NOT NULL,
    TYPE         VARCHAR2(20),
    MAX_STUDENTS NUMBER,
    CONSTRAINT SYS_C008705 PRIMARY KEY (EXAM_ID),
    CONSTRAINT FK_EXAM_COURSE FOREIGN KEY (COURSE_ID) REFERENCES FTIAPP.COURSES(COURSE_ID),
    CONSTRAINT FK_EXAM_PROGRAM FOREIGN KEY (PROGRAM_ID) REFERENCES FTIAPP.PROGRAMS(PROGRAM_ID)
);

CREATE TABLE FTIAPP.EXAM_ROOMS (
    EXAM_ID NUMBER NOT NULL,
    ROOM_ID NUMBER NOT NULL,
    CONSTRAINT PK_EXAM_ROOMS PRIMARY KEY (EXAM_ID, ROOM_ID),
    CONSTRAINT FK_EXAMROOM_EXAMS FOREIGN KEY (EXAM_ID) REFERENCES FTIAPP.EXAMS_SCHEDULE(EXAM_ID),
    CONSTRAINT FK_EXAMROOM_ROOMS FOREIGN KEY (ROOM_ID) REFERENCES FTIAPP.ROOMS(ROOM_ID)
);

CREATE TABLE FTIAPP.EXAM_ATTENDANCE (
    EXAM_ATTENDANCE_ID NUMBER DEFAULT "FTIAPP"."ISEQ$$_99562".nextval NOT NULL,
    EXAM_ID            NUMBER NOT NULL,
    STUDENT_ID         NUMBER NOT NULL,
    STATUS             VARCHAR2(20) DEFAULT 'present',
    CONSTRAINT SYS_C008716 PRIMARY KEY (EXAM_ATTENDANCE_ID),
    CONSTRAINT UC_EXAM_STUDENT UNIQUE (EXAM_ID, STUDENT_ID),
    CONSTRAINT FK_EXAM_ATTENDANCE_EXAM FOREIGN KEY (EXAM_ID) REFERENCES FTIAPP.EXAMS_SCHEDULE(EXAM_ID),
    CONSTRAINT FK_EXAM_ATTENDANCE_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES FTIAPP.STUDENTS(STUDENT_ID)
);

CREATE TABLE FTIAPP.COURSE_SCHEDULE (
    SCHEDULE_ID        NUMBER DEFAULT "FTIAPP"."ISEQ$$_99543".nextval NOT NULL,
    TEACHING_COURSE_ID NUMBER NOT NULL,
    CLASS_ID           NUMBER NOT NULL,
    DAY_OF_WEEK        VARCHAR2(10) NOT NULL,
    START_TIME         TIMESTAMP(6) NOT NULL,
    END_TIME           TIMESTAMP(6) NOT NULL,
    SEMESTER           VARCHAR2(10),
    ACADEMIC_YEAR      VARCHAR2(9),
    TYPE_ID            NUMBER,
    ROOM_ID            NUMBER,
    CONSTRAINT SYS_C008693 PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT SYS_C008694 FOREIGN KEY (TEACHING_COURSE_ID) REFERENCES FTIAPP.TEACHING_COURSES(TEACHING_COURSE_ID),
    CONSTRAINT SYS_C008695 FOREIGN KEY (CLASS_ID) REFERENCES FTIAPP.CLASSES(CLASS_ID),
    CONSTRAINT FK_SCHEDULE_TYPE FOREIGN KEY (TYPE_ID) REFERENCES FTIAPP.COURSE_TYPES(TYPE_ID),
    CONSTRAINT FK_SCHEDULE_ROOM FOREIGN KEY (ROOM_ID) REFERENCES FTIAPP.ROOMS(ROOM_ID)
);
