ALTER TABLE FTIAPP.COURSES ADD (
    KREDITE_LEKSION NUMBER(3,1) DEFAULT 0.0,
    KREDITE_SEMINAR NUMBER(3,1) DEFAULT 0.0,
    KREDITE_LABORATOR NUMBER(3,1) DEFAULT 0.0,
    KREDITE_DETYRE_KURSI NUMBER(3,1) DEFAULT 0.0,
    KREDITE_PRAKTIKE NUMBER(3,1) DEFAULT 0.0
);
