-- Përditësimi i krediteve të detajuara për lëndët e Vitit 1 (Inxhinieri Kompjuterike - Diplomë e Dyfishtë)

-- 1. Gjuhë e huaj 1 - (frëngjisht) [Totali: 7]
UPDATE FTIAPP.COURSES 
SET KREDITE = 7,
    KREDITE_LEKSION = 3.5,
    KREDITE_SEMINAR = 0.0,
    KREDITE_LABORATOR = 3.5,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%gjuhe e huaj 1%' OR LOWER(EMRI_COURSE) LIKE '%gjuhë e huaj 1%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 2. Analizë Matematike 1 [Totali: 6]
UPDATE FTIAPP.COURSES 
SET KREDITE = 6,
    KREDITE_LEKSION = 3.0,
    KREDITE_SEMINAR = 3.0,
    KREDITE_LABORATOR = 0.0,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%analize matematike 1%' OR LOWER(EMRI_COURSE) LIKE '%analizë matematike 1%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 3. Fizikë e përgjithshme [Totali: 6]
UPDATE FTIAPP.COURSES 
SET KREDITE = 6,
    KREDITE_LEKSION = 3.0,
    KREDITE_SEMINAR = 2.5,
    KREDITE_LABORATOR = 0.5,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%fizike e pergjithshme%' OR LOWER(EMRI_COURSE) LIKE '%fizikë e përgjithshme%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 4. Elementet e Informatikës [Totali: 6]
UPDATE FTIAPP.COURSES 
SET KREDITE = 6,
    KREDITE_LEKSION = 3.0,
    KREDITE_SEMINAR = 2.0,
    KREDITE_LABORATOR = 0.5,
    KREDITE_DETYRE_KURSI = 0.5,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%elementet e informatikes%' OR LOWER(EMRI_COURSE) LIKE '%elementet e informatikës%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 5. Algjebër dhe Gjeometri [Totali: 5]
UPDATE FTIAPP.COURSES 
SET KREDITE = 5,
    KREDITE_LEKSION = 3.0,
    KREDITE_SEMINAR = 2.0,
    KREDITE_LABORATOR = 0.0,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%algjeber%' OR LOWER(EMRI_COURSE) LIKE '%algjebër%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 6. Gjuhë e huaj 2 - (frëngjisht) [Totali: 8]
UPDATE FTIAPP.COURSES 
SET KREDITE = 8,
    KREDITE_LEKSION = 4.0,
    KREDITE_SEMINAR = 0.0,
    KREDITE_LABORATOR = 4.0,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%gjuhe e huaj 2%' OR LOWER(EMRI_COURSE) LIKE '%gjuhë e huaj 2%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 7. Analizë Matematike 2 [Totali: 5]
UPDATE FTIAPP.COURSES 
SET KREDITE = 5,
    KREDITE_LEKSION = 3.0,
    KREDITE_SEMINAR = 2.0,
    KREDITE_LABORATOR = 0.0,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%analize matematike 2%' OR LOWER(EMRI_COURSE) LIKE '%analizë matematike 2%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 8. Elektroteknikë [Totali: 6]
UPDATE FTIAPP.COURSES 
SET KREDITE = 6,
    KREDITE_LEKSION = 3.5,
    KREDITE_SEMINAR = 2.0,
    KREDITE_LABORATOR = 0.5,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%elektroteknike%' OR LOWER(EMRI_COURSE) LIKE '%elektroteknikë%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 9. Legjislacioni në TIK [Totali: 3]
UPDATE FTIAPP.COURSES 
SET KREDITE = 3,
    KREDITE_LEKSION = 2.0,
    KREDITE_SEMINAR = 1.0,
    KREDITE_LABORATOR = 0.0,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%legjislacion%' OR LOWER(EMRI_COURSE) LIKE '%legjislacioni%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 10. Teknikat dhe gjuhët e programimit [Totali: 6]
UPDATE FTIAPP.COURSES 
SET KREDITE = 6,
    KREDITE_LEKSION = 3.0,
    KREDITE_SEMINAR = 2.0,
    KREDITE_LABORATOR = 0.5,
    KREDITE_DETYRE_KURSI = 0.5,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%teknikat dhe gjuhet%' OR LOWER(EMRI_COURSE) LIKE '%teknikat dhe gjuhët%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);

-- 11. Analizë Matematike 3 [Totali: 2]
UPDATE FTIAPP.COURSES 
SET KREDITE = 2,
    KREDITE_LEKSION = 1.0,
    KREDITE_SEMINAR = 1.0,
    KREDITE_LABORATOR = 0.0,
    KREDITE_DETYRE_KURSI = 0.0,
    KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(EMRI_COURSE) LIKE '%analize matematike 3%' OR LOWER(EMRI_COURSE) LIKE '%analizë matematike 3%')
  AND (STUDY_YEAR = 1 OR STUDY_YEAR IS NULL);
