-- Përditësimi i krediteve të detajuara për lëndët e Vitit 1 (Inxhinieri Informatike - Bachelor)

-- 1. Gjuhë e huaj 1 [Totali: 5]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 5,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 2.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%gjuhe e huaj 1%' OR LOWER(c.EMRI_COURSE) LIKE '%gjuhë e huaj 1%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 2. Analizë Matematike 1 [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 3.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%analize matematike 1%' OR LOWER(c.EMRI_COURSE) LIKE '%analizë matematike 1%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 3. Fizikë 1 [Totali: 5]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 5,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%fizike 1%' OR LOWER(c.EMRI_COURSE) LIKE '%fizikë 1%' OR LOWER(c.EMRI_COURSE) LIKE '%fizike i%' OR LOWER(c.EMRI_COURSE) LIKE '%fizikë i%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 4. Elementet e Informatikës [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 2.0,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%elementet e informatikes%' OR LOWER(c.EMRI_COURSE) LIKE '%elementet e informatikës%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 5. Algjebër dhe Gjeometri [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 3.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%algjeber%' OR LOWER(c.EMRI_COURSE) LIKE '%algjebër%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 6. Shkrim dhe Prezantim Akademik [Totali: 2]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 2,
    c.KREDITE_LEKSION = 1.5,
    c.KREDITE_SEMINAR = 0.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%shkrim%prezantim%' OR LOWER(c.EMRI_COURSE) LIKE '%prezantim akademik%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 7. Analizë Matematike 2 [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 3.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%analize matematike 2%' OR LOWER(c.EMRI_COURSE) LIKE '%analizë matematike 2%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 8. Fizikë 2 [Totali: 5]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 5,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%fizike 2%' OR LOWER(c.EMRI_COURSE) LIKE '%fizikë 2%' OR LOWER(c.EMRI_COURSE) LIKE '%fizike ii%' OR LOWER(c.EMRI_COURSE) LIKE '%fizikë ii%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 9. Elektroteknikë [Totali: 5]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 5,
    c.KREDITE_LEKSION = 3.5,
    c.KREDITE_SEMINAR = 1.0,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%elektroteknike%' OR LOWER(c.EMRI_COURSE) LIKE '%elektroteknikë%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 10. Analizë Matematike 3 [Totali: 3]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 3,
    c.KREDITE_LEKSION = 2.0,
    c.KREDITE_SEMINAR = 1.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%analize matematike 3%' OR LOWER(c.EMRI_COURSE) LIKE '%analizë matematike 3%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 11. Teknikat dhe gjuhët e programimit [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 2.0,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%teknikat dhe gjuhet%' OR LOWER(c.EMRI_COURSE) LIKE '%teknikat dhe gjuhët%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 12. Probabiliteti [Totali: 5]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 5,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 2.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%probabilitet%' OR LOWER(c.EMRI_COURSE) LIKE '%probabiliteti%')
  AND (c.STUDY_YEAR = 1 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));
