ALTER TABLE FTIAPP.USERS ADD (
    VERIFIED           CHAR(1)      DEFAULT 'N' NOT NULL,
    VERIFICATION_CODE  VARCHAR2(6),
    CODE_CREATED_AT    TIMESTAMP
);

ALTER TABLE FTIAPP.USERS ADD CONSTRAINT CHK_USERS_VERIFIED CHECK (VERIFIED IN ('Y', 'N'));

ALTER TABLE FTIAPP.STUDENTS ADD NR_MATRIKULIMIT VARCHAR2(12);

CREATE TABLE FTIAPP.STUDENT_PRE_ENROLLMENT (
    ENROLLMENT_ID    INTEGER             NOT NULL,
    EMRI             VARCHAR2(50)        NOT NULL,
    MBIEMRI          VARCHAR2(50)        NOT NULL,
    EMAIL            VARCHAR2(100)       NOT NULL,
    NR_MATRIKULIMIT  VARCHAR2(12)        NOT NULL,
    PROGRAM_ID       INTEGER,
    VIT_STUDIMIT     INTEGER,
    CLASS_ID         INTEGER,
    CONSTRAINT PK_STUDENT_PRE_ENROLLMENT PRIMARY KEY (ENROLLMENT_ID),
    CONSTRAINT UQ_ENROLLMENT_MATRIKULIMI  UNIQUE (NR_MATRIKULIMIT),
    CONSTRAINT UQ_ENROLLMENT_EMAIL        UNIQUE (EMAIL),
    CONSTRAINT FK_ENROLL_PROGRAM    FOREIGN KEY (PROGRAM_ID)
        REFERENCES FTIAPP.PROGRAMS(PROGRAM_ID),
    CONSTRAINT FK_ENROLL_CLASS      FOREIGN KEY (CLASS_ID)
        REFERENCES FTIAPP.CLASSES(CLASS_ID)
);

CREATE SEQUENCE FTIAPP.SEQ_ENROLLMENT START WITH 1 INCREMENT BY 1 NOCACHE;
