-- Përditësimi i krediteve të detajuara për lëndët e Vitit 3 (Inxhinieri Informatike - Bachelor)

-- 1. Algoritmikë [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.5,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%algoritmik%' OR LOWER(c.EMRI_COURSE) LIKE '%algoritmike%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 2. Rrjetat e Kompjuterave [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.5,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%rrjeta%kompjuter%' OR LOWER(c.EMRI_COURSE) LIKE '%rrjetat e kompjuterave%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 3. Programim Web [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.5,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%programim%web%' OR LOWER(c.EMRI_COURSE) LIKE '%web%programim%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 4. Inxhinieri Softi [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.5,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%inxhinieri soft%' OR LOWER(c.EMRI_COURSE) LIKE '%inxhinieri softueri%' OR LOWER(c.EMRI_COURSE) LIKE '%inxhinieri softi%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 5. Sistemet Operative [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.5,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%sistemet operative%' OR LOWER(c.EMRI_COURSE) LIKE '%sistem operativ%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 6. Teknikat e përpunimit të të dhënave në Python [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.5,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%python%' OR LOWER(c.EMRI_COURSE) LIKE '%teknikat e perpunimit%' OR LOWER(c.EMRI_COURSE) LIKE '%teknikat e përpunimit%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 7. Sistemet e shpërndara dhe reja kompjuterike [Totali: 6]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 6,
    c.KREDITE_LEKSION = 3.5,
    c.KREDITE_SEMINAR = 1.5,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%sistemet e shperndara%' OR LOWER(c.EMRI_COURSE) LIKE '%sistemet e shpërndara%' OR LOWER(c.EMRI_COURSE) LIKE '%reja kompjuterike%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 8. Siguria Kibernetike [Totali: 5]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 5,
    c.KREDITE_LEKSION = 3.0,
    c.KREDITE_SEMINAR = 1.0,
    c.KREDITE_LABORATOR = 0.5,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%siguria kibernetike%' OR LOWER(c.EMRI_COURSE) LIKE '%siguri kibernetike%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 9. Legjislacioni në TIK [Totali: 3]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 3,
    c.KREDITE_LEKSION = 2.0,
    c.KREDITE_SEMINAR = 0.5,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.5,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%legjislacion%' OR LOWER(c.EMRI_COURSE) LIKE '%legjislacioni%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 10. Praktikë [Totali: 4]
UPDATE FTIAPP.COURSES c
SET c.KREDITE = 4,
    c.KREDITE_LEKSION = 0.0,
    c.KREDITE_SEMINAR = 0.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 4.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%praktike%' OR LOWER(c.EMRI_COURSE) LIKE '%praktikë%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));

-- 11. Diplomë
UPDATE FTIAPP.COURSES c
SET c.KREDITE_LEKSION = 0.0,
    c.KREDITE_SEMINAR = 0.0,
    c.KREDITE_LABORATOR = 0.0,
    c.KREDITE_DETYRE_KURSI = 0.0,
    c.KREDITE_PRAKTIKE = 0.0
WHERE (LOWER(c.EMRI_COURSE) LIKE '%diplome%' OR LOWER(c.EMRI_COURSE) LIKE '%diplomë%')
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (c.PROGRAM_ID IN (
      SELECT p.PROGRAM_ID FROM FTIAPP.PROGRAMS p 
      WHERE LOWER(p.SPECIALIZIMI) LIKE '%informatik%' 
        AND (p.DIPLOME_DYFISHTE IS NULL OR LOWER(p.DIPLOME_DYFISHTE) = 'jo')
  ));
