ALTER TABLE COURSES ADD (
    SEMESTER VARCHAR2(10) DEFAULT '1',
    DURATION_WEEKS NUMBER(3) DEFAULT 18
);

UPDATE COURSES c
SET SEMESTER = (
    SELECT tc.SEMESTER 
    FROM TEACHING_COURSES tc 
    WHERE tc.COURSE_ID = c.COURSE_ID 
      AND tc.SEMESTER IS NOT NULL 
      AND ROWNUM = 1
)
WHERE EXISTS (
    SELECT 1 
    FROM TEACHING_COURSES tc 
    WHERE tc.COURSE_ID = c.COURSE_ID 
      AND tc.SEMESTER IS NOT NULL
);

UPDATE COURSES c
SET DURATION_WEEKS = (
    SELECT tc.DURATION_WEEKS 
    FROM TEACHING_COURSES tc 
    WHERE tc.COURSE_ID = c.COURSE_ID 
      AND tc.DURATION_WEEKS IS NOT NULL 
      AND ROWNUM = 1
)
WHERE EXISTS (
    SELECT 1 
    FROM TEACHING_COURSES tc 
    WHERE tc.COURSE_ID = c.COURSE_ID 
      AND tc.DURATION_WEEKS IS NOT NULL
);
