UPDATE COURSES c
SET DURATION_WEEKS = 14
WHERE PROGRAM_ID IN (
    SELECT PROGRAM_ID 
    FROM PROGRAMS 
    WHERE LOWER(NIVEL) LIKE '%bachelor%'
);

UPDATE COURSES c
SET DURATION_WEEKS = 12
WHERE PROGRAM_ID IN (
    SELECT PROGRAM_ID 
    FROM PROGRAMS 
    WHERE LOWER(NIVEL) LIKE '%master%'
);
