ALTER TABLE TEACHING_COURSES ADD WEEKLY_HOURS INT DEFAULT 2;

UPDATE TEACHING_COURSES SET WEEKLY_HOURS = 2 WHERE ROLE_TYPE = 'LEKSION';
UPDATE TEACHING_COURSES SET WEEKLY_HOURS = 2 WHERE ROLE_TYPE = 'SEMINAR';
UPDATE TEACHING_COURSES SET WEEKLY_HOURS = 1 WHERE ROLE_TYPE IN ('LABORATOR', 'LAB');
UPDATE TEACHING_COURSES SET WEEKLY_HOURS = 1 WHERE ROLE_TYPE IN ('DETYRE_KURSI', 'DETYRE', 'DETYRA');
UPDATE TEACHING_COURSES SET WEEKLY_HOURS = 2 WHERE ROLE_TYPE IN ('PRAKTIKE', 'PRAKTIK');
