-- Përditësimi i Semestrit dhe Kohëzgjatjes për Inxhinieri Kompjuterike Viti 1 (Program ID: 5)

-- Semestri 1 (Javë 14)
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 105; -- Gjuhë e huaj 1 – (frëngjisht)
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 106; -- Analizë Matematike 1
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 107; -- Fizikë e përgjithshme
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 108; -- Elementet e Informatikës
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 109; -- Algjebër dhe Gjeometri

-- Semestri 2 (Javë 14)
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 110; -- Gjuhë e huaj 2 – (frëngjisht)
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 111; -- Analizë Matematike 2
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 112; -- Elektroteknikë
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 113; -- Legjislacioni në TIK
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 114; -- Teknikat dhe gjuhët e programimit
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 115; -- Analizë Matematike 3

-- Pastrimi i alokimeve të vjetra për këto lëndë
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES 
WHERE TEACHING_COURSE_ID IN (
    SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES 
    WHERE COURSE_ID IN (105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115)
);

DELETE FROM FTIAPP.TEACHING_COURSES 
WHERE COURSE_ID IN (105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115);

-- Krijimi i alokimeve të reja me orët javore dhe totale

-- Semestri 1
-- 105: Gjuhë e huaj 1 – (frëngjisht) (4h Leksion | 2h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (105, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 4.0, 56);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (105, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 28);

-- 106: Analizë Matematike 1 (2.5h Leksion | 3h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (106, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 35);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (106, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 3.0, 42);

-- 107: Fizikë e përgjithshme (2.5h Leksion | 2h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (107, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 35);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (107, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 28);

-- 108: Elementet e Informatikës (2.5h Leksion | 2h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (108, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 35);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (108, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 28);

-- 109: Algjebër dhe Gjeometri (2.5h Leksion | 3h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (109, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 35);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (109, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 3.0, 42);

-- Semestri 2
-- 110: Gjuhë e huaj 2 – (frëngjisht) (3h Leksion | 1.5h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (110, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 3.0, 42);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (110, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 1.5, 21);

-- 111: Analizë Matematike 2 (2.5h Leksion | 3h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (111, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 35);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (111, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 3.0, 42);

-- 112: Elektroteknikë (3h Leksion | 2h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (112, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 3.0, 42);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (112, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 28);

-- 113: Legjislacioni në TIK (2h Leksion | 1h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (113, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.0, 28);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (113, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 1.0, 14);

-- 114: Teknikat dhe gjuhët e programimit (2.5h Leksion | 2h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (114, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 35);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (114, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 28);

-- 115: Analizë Matematike 3 (1h Leksion | 1h Seminar)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (115, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 1.0, 14);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (115, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 1.0, 14);
