-- Ndryshimi i sigurt i TOTAL_HOURS në FLOAT në Oracle
ALTER TABLE FTIAPP.TEACHING_COURSES ADD TOTAL_HOURS_TMP FLOAT;
UPDATE FTIAPP.TEACHING_COURSES SET TOTAL_HOURS_TMP = TOTAL_HOURS;
UPDATE FTIAPP.TEACHING_COURSES SET TOTAL_HOURS = NULL;
ALTER TABLE FTIAPP.TEACHING_COURSES MODIFY TOTAL_HOURS FLOAT;
UPDATE FTIAPP.TEACHING_COURSES SET TOTAL_HOURS = TOTAL_HOURS_TMP;
ALTER TABLE FTIAPP.TEACHING_COURSES DROP COLUMN TOTAL_HOURS_TMP;

-- Përditësimi i Semestrit dhe Kohëzgjatjes për Inxhinieri Kompjuterike Viti 1 (Program ID: 5)
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 105; -- Gjuhë e huaj 1 – (frëngjisht)
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 106; -- Analizë Matematike 1
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 107; -- Fizikë e përgjithshme
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 108; -- Elementet e Informatikës
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 109; -- Algjebër dhe Gjeometri

UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 110; -- Gjuhë e huaj 2 – (frëngjisht)
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 111; -- Analizë Matematike 2
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 112; -- Elektroteknikë
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 113; -- Legjislacioni në TIK
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 114; -- Teknikat dhe gjuhët e programimit
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 115; -- Analizë Matematike 3

-- Pastrimi i alokimeve ekzistuese për këto lëndë
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES 
WHERE TEACHING_COURSE_ID IN (
    SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES 
    WHERE COURSE_ID IN (105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115)
);

DELETE FROM FTIAPP.TEACHING_COURSES 
WHERE COURSE_ID IN (105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115);

-- SEMESTRI 1

-- 105: Gjuhë e huaj 1 – (frëngjisht)
-- Ngarkesa javore: 4 orë Leksion | 2 orë Seminar
-- Orët Totale: 42 orë Leksione | 0 orë Seminare | 70 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (105, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 4.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (105, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 0.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (105, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LABORATOR', 0.0, 70.0);

-- 106: Analizë Matematike 1
-- Ngarkesa javore: 2.5 orë Leksion | 3 orë Seminar
-- Orët Totale: 36 orë Leksione | 42 orë Seminare | 0 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (106, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (106, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 3.0, 42.0);

-- 107: Fizikë e përgjithshme
-- Ngarkesa javore: 2.5 orë Leksion | 2 orë Seminar
-- Orët Totale: 36 orë Leksione | 35 orë Seminare | 10 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (107, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (107, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 35.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (107, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LABORATOR', 0.0, 10.0);

-- 108: Elementet e Informatikës
-- Ngarkesa javore: 2.5 orë Leksion | 2 orë Seminar
-- Orët Totale: 36 orë Leksione | 28 orë Seminare | 10 orë Laboratore | 2.5 orë Detyra/Projekte
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (108, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (108, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 28.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (108, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (108, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'DETYRE_KURSI', 0.0, 2.5);

-- 109: Algjebër dhe Gjeometri
-- Ngarkesa javore: 2.5 orë Leksion | 3 orë Seminar
-- Orët Totale: 36 orë Leksione | 28 orë Seminare | 0 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (109, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (109, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 3.0, 28.0);

-- SEMESTRI 2

-- 110: Gjuhë e huaj 2 – (frëngjisht)
-- Ngarkesa javore: 3 orë Leksion | 1.5 orë Seminar
-- Orët Totale: 48 orë Leksione | 0 orë Seminare | 80 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (110, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 3.0, 48.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (110, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 1.5, 0.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (110, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LABORATOR', 0.0, 80.0);

-- 111: Analizë Matematike 2
-- Ngarkesa javore: 2.5 orë Leksion | 3 orë Seminar
-- Orët Totale: 36 orë Leksione | 28 orë Seminare | 0 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (111, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (111, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 3.0, 28.0);

-- 112: Elektroteknikë
-- Ngarkesa javore: 3 orë Leksion | 2 orë Seminar
-- Orët Totale: 42 orë Leksione | 28 orë Seminare | 10 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (112, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (112, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 28.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (112, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LABORATOR', 0.0, 10.0);

-- 113: Legjislacioni në TIK
-- Ngarkesa javore: 2 orë Leksion | 1 orë Seminar
-- Orët Totale: 24 orë Leksione | 14 orë Seminare | 0 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (113, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (113, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 1.0, 14.0);

-- 114: Teknikat dhe gjuhët e programimit
-- Ngarkesa javore: 2.5 orë Leksion | 2 orë Seminar
-- Orët Totale: 36 orë Leksione | 28 orë Seminare | 10 orë Laboratore | 2.5 orë Detyra/Projekte
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (114, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (114, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 2.0, 28.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (114, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (114, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'DETYRE_KURSI', 0.0, 2.5);

-- 115: Analizë Matematike 3
-- Ngarkesa javore: 1 orë Leksion | 1 orë Seminar
-- Orët Totale: 12 orë Leksione | 14 orë Seminare | 0 orë Laboratore
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (115, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'LEKSION', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (115, (SELECT MIN(PROFESSOR_ID) FROM FTIAPP.PROFESSORS), 'SEMINAR', 1.0, 14.0);
