-- Përditësimi i Semestrit dhe Kohëzgjatjes për Inxhinieri Kompjuterike Viti 2 (Program ID: 5)

-- Semestri 1 (Javë 14)
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 116; -- Gjuhë e huaj 3
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 117; -- Bazat e të dhënave
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 118; -- Programimi i orientuar nga objekti
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 119; -- Sinjale dhe Sisteme
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 120; -- Ekonomi dhe Menaxhim
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 121; -- Elementet dhe teknologjitë elektronike

-- Semestri 2 (Javë 14)
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 122; -- Arkitekturë e kompjuterave
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 123; -- Algoritmikë dhe strukturë të dhënash
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 124; -- Analizë numerike
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 125; -- Hyrje në Automatizim
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 126; -- Probabiliteti dhe statistika

-- Pastrimi i alokimeve ekzistuese për këto lëndë
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES 
WHERE TEACHING_COURSE_ID IN (
    SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES 
    WHERE COURSE_ID IN (116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126)
);

DELETE FROM FTIAPP.TEACHING_COURSES 
WHERE COURSE_ID IN (116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126);

-- SEMESTRI 1 (Viti 2)

-- 116: Gjuhë e huaj 3 (4h L | 2h S | Tot: 18h L, 0h S, 30h Lab)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (116, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 4.0, 18.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (116, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 2.0, 0.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (116, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LABORATOR', 0.0, 30.0);

-- 117: Bazat e të dhënave (3h L | 1.5h S | Tot: 42h L, 21h S, 10h Lab, 2.5h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (117, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (117, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (117, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (117, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'DETYRE_KURSI', 0.0, 2.5);

-- 118: Programimi i orientuar nga objekti (3h L | 1.5h S | Tot: 42h L, 21h S, 10h Lab, 2.5h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (118, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (118, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (118, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (118, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'DETYRE_KURSI', 0.0, 2.5);

-- 119: Sinjale dhe Sisteme (3h L | 1.5h S | Tot: 42h L, 21h S, 10h Lab, 2.5h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (119, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (119, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (119, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (119, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'DETYRE_KURSI', 0.0, 2.5);

-- 120: Ekonomi dhe Menaxhim (2h L | 1.5h S | Tot: 36h L, 14h S, 0h Lab, 0h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (120, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'LEKSION', 2.0, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (120, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'SEMINAR', 1.5, 14.0);

-- 121: Elementet dhe teknologjitë elektronike (3h L | 1.5h S | Tot: 36h L, 21h S, 10h Lab, 0h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (121, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'LEKSION', 3.0, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (121, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (121, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'LABORATOR', 0.0, 10.0);

-- SEMESTRI 2 (Viti 2)

-- 122: Arkitekturë e kompjuterave (3h L | 1.5h S | Tot: 42h L, 28h S, 10h Lab, 0h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (122, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (122, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'SEMINAR', 1.5, 28.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (122, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'LABORATOR', 0.0, 10.0);

-- 123: Algoritmikë dhe strukturë të dhënash (3h L | 1.5h S | Tot: 42h L, 21h S, 10h Lab, 2.5h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (123, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (123, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (123, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (123, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'DETYRE_KURSI', 0.0, 2.5);

-- 124: Analizë numerike (3h L | 2h S | Tot: 42h L, 28h S, 0h Lab, 2.5h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (124, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (124, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'SEMINAR', 2.0, 28.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (124, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'DETYRE_KURSI', 0.0, 2.5);

-- 125: Hyrje në Automatizim (3h L | 1.5h S | Tot: 42h L, 21h S, 10h Lab, 2.5h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (125, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (125, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (125, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (125, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'DETYRE_KURSI', 0.0, 2.5);

-- 126: Probabiliteti dhe statistika (2.5h L | 2.5h S | Tot: 36h L, 35h S, 0h Lab, 2.5h Detyre)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (126, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (126, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'SEMINAR', 2.5, 35.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (126, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'DETYRE_KURSI', 0.0, 2.5);
