-- Përditësimi i Semestrit dhe Kohëzgjatjes për Inxhinieri Informatike Viti 1 (Program ID: 1)

-- Semestri 1 (Javë 14)
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 281; -- Gjuhë e huaj 1
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 4;   -- Analizë Matematike 1
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 5;   -- Fizikë 1
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 6;   -- Elementet e Informatikës
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 7;   -- Algjebër dhe Gjeometri
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 8;   -- Shkrim dhe Prezantim Akademik

-- Semestri 2 (Javë 14)
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 9;   -- Analizë Matematike 2
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 10;  -- Fizikë 2
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 11;  -- Elektroteknikë
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 12;  -- Analizë Matematike 3
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 13;  -- Teknikat dhe gjuhët e programimit
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 14;  -- Probabiliteti

-- Pastrimi i alokimeve ekzistuese dhe referencave per keto lende
DELETE FROM FTIAPP.ATTENDANCE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (281, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14));
DELETE FROM FTIAPP.GRADES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (281, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14));
DELETE FROM FTIAPP.TOPICS WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (281, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14));
DELETE FROM FTIAPP.FAILED_COURSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (281, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14));
DELETE FROM FTIAPP.COURSE_SCHEDULE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (281, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14));
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (281, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14));
DELETE FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (281, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14);

-- SEMESTRI 1 (Viti 1 - Inxhinieri Informatike)

-- 281: Gjuhë e huaj 1 (2.5h L | 2h S | Tot: 36h L, 28h S, 0h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (281, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (281, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 2.0, 28.0);

-- 4: Analizë Matematike 1 (2.5h L | 3h S | Tot: 36h L, 42h S, 0h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (4, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (4, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'SEMINAR', 3.0, 42.0);

-- 5: Fizikë 1 (2.5h L | 1.5h S | Tot: 36h L, 21h S, 10h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (5, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (5, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (5, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LABORATOR', 0.0, 10.0);

-- 6: Elementet e Informatikës (2.5h L | 2h S | Tot: 36h L, 28h S, 10h Lab, 2.5h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (6, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (6, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 2.0, 28.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (6, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (6, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'DETYRE_KURSI', 0.0, 2.5);

-- 7: Algjebër dhe Gjeometri (2.5h L | 3h S | Tot: 36h L, 42h S, 0h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (7, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (7, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'SEMINAR', 3.0, 42.0);

-- 8: Shkrim dhe Prezantim Akademik (1.5h L | 0h S | Tot: 18h L, 0h S, 0h Lab, 2.5h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (8, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LEKSION', 1.5, 18.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (8, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'DETYRE_KURSI', 0.0, 2.5);

-- SEMESTRI 2 (Viti 1 - Inxhinieri Informatike)

-- 9: Analizë Matematike 2 (2.5h L | 3h S | Tot: 36h L, 42h S, 0h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (9, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (9, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'SEMINAR', 3.0, 42.0);

-- 10: Fizikë 2 (2.5h L | 1.5h S | Tot: 36h L, 21h S, 10h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (10, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (10, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (10, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'LABORATOR', 0.0, 10.0);

-- 11: Elektroteknikë (3h L | 1h S | Tot: 42h L, 14h S, 10h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (11, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (11, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'SEMINAR', 1.0, 14.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (11, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'LABORATOR', 0.0, 10.0);

-- 12: Analizë Matematike 3 (2h L | 1h S | Tot: 24h L, 14h S, 0h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (12, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LEKSION', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (12, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'SEMINAR', 1.0, 14.0);

-- 13: Teknikat dhe gjuhët e programimit (2.5h L | 2h S | Tot: 36h L, 28h S, 10h Lab, 2.5h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (13, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (13, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'SEMINAR', 2.0, 28.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (13, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (13, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'DETYRE_KURSI', 0.0, 2.5);

-- 14: Probabiliteti (2.5h L | 2h S | Tot: 36h L, 28h S, 0h Lab, 0h Detyrë)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (14, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'LEKSION', 2.5, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS)
VALUES (14, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'SEMINAR', 2.0, 28.0);
