-- V48: Configure Semester and Teaching Courses breakdown for Inxhinieri Informatike Bachelor - Year 3
-- Program ID: 1, Year: 3

-- Step 1: Update SEMESTER and DURATION_WEEKS on COURSES table
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 26; -- Algoritmikë
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 27; -- Rrjetat e Kompjuterave
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 28; -- Programim Web
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 29; -- Inxhinieri Softi
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 14 WHERE COURSE_ID = 30; -- Sistemet Operative

UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 31; -- Teknikat e përpunimit të të dhënave në Python
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 32; -- Sistemet e shpërndara dhe reja kompjuterike
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 33; -- Siguria Kibernetike
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 36; -- Legjislacioni ne TIK
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 34; -- Praktikë
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 14 WHERE COURSE_ID = 35; -- Diplomë

-- Step 2: Clean up any dependent child tables referencing old TEACHING_COURSES for Year 3
DELETE FROM FTIAPP.ATTENDANCE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36));
DELETE FROM FTIAPP.GRADES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36));
DELETE FROM FTIAPP.TOPICS WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36));
DELETE FROM FTIAPP.FAILED_COURSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36));
DELETE FROM FTIAPP.COURSE_SCHEDULE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36));
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36));
DELETE FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36);

-- Step 3: Insert Teaching Courses for Semestri 1
-- Course 26: Algoritmikë
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (26, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (26, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (26, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (26, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 27: Rrjetat e Kompjuterave
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (27, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (27, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (27, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (27, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 8), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 28: Programim Web
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (28, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 9), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (28, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 10), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (28, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 11), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (28, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 12), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 29: Inxhinieri Softi
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (29, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 13), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (29, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 14), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (29, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 15), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (29, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 16), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 30: Sistemet Operative
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (30, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 17), 'LEKSION', 3.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (30, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 18), 'SEMINAR', 1.5, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (30, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 19), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (30, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 20), 'DETYRE_KURSI', 0.0, 2.5);

-- Step 4: Insert Teaching Courses for Semestri 2
-- Course 31: Teknikat e përpunimit të të dhënave në Python
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (31, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 4.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (31, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 2.0, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (31, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (31, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 32: Sistemet e shpërndara dhe reja kompjuterike
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (32, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LEKSION', 4.0, 42.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (32, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'SEMINAR', 2.0, 21.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (32, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (32, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 8), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 33: Siguria Kibernetike
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (33, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 9), 'LEKSION', 3.0, 36.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (33, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 10), 'SEMINAR', 2.0, 14.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (33, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 11), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (33, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 12), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 36: Legjislacioni ne TIK
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (36, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 13), 'LEKSION', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (36, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 14), 'SEMINAR', 1.0, 7.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (36, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 15), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 34: Praktikë
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (34, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 16), 'PRAKTIKE', 0.0, 80.0);

-- Course 35: Diplomë
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (35, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 17), 'DIPLOME', 0.0, 30.0);
