-- V49: Configure Semester, Duration Weeks and Teaching Courses breakdown for Inteligjence Artificiale dhe Optimizim Master - Year 1
-- Program: Inteligjencë Artificiale dhe Optimizim (Master Shkencor), Study Year: 1, Duration: 12 weeks

-- Step 1: Update SEMESTER and DURATION_WEEKS on COURSES table
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 153; -- Statistikë
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 154; -- Inteligjencë Artificiale
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 155; -- Cloud Computing
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 156; -- Baza të Dhënash të Avancuara
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 157; -- Programim i Avancuar
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 158; -- Gjuhë Frënge 1

UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 159; -- Kërkime Operacionale
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 160; -- Inxhinieri Softuere e Avancuar
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 161; -- Inxhinieria e Sistemeve Komplekse
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 162; -- Machine Learning
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 163; -- Computer Vision

-- Step 2: Clean up any dependent child tables referencing old TEACHING_COURSES for Year 1 AI
DELETE FROM FTIAPP.ATTENDANCE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163));
DELETE FROM FTIAPP.GRADES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163));
DELETE FROM FTIAPP.TOPICS WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163));
DELETE FROM FTIAPP.FAILED_COURSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163));
DELETE FROM FTIAPP.COURSE_SCHEDULE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163));
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163));
DELETE FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163);

-- Step 3: Insert Teaching Courses for Semestri 1
-- Course 153: Statistikë
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (153, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (153, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (153, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 154: Inteligjencë Artificiale
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (154, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (154, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (154, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (154, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 155: Cloud Computing
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (155, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 8), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (155, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 9), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (155, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 10), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (155, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 11), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 156: Baza të Dhënash të Avancuara
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (156, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 12), 'LEKSION', 2.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (156, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 13), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (156, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 14), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (156, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 15), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 157: Programim i Avancuar
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (157, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 16), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (157, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 17), 'SEMINAR', 0.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (157, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 18), 'LABORATOR', 0.0, 10.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (157, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 19), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 158: Gjuhë Frënge 1
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (158, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 20), 'LEKSION', 2.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (158, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'SEMINAR', 1.0, 12.0);

-- Step 4: Insert Teaching Courses for Semestri 2
-- Course 159: Kërkime Operacionale
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (159, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (159, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (159, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (159, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 160: Inxhinieri Softuere e Avancuar
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (160, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (160, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (160, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 8), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (160, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 9), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 161: Inxhinieria e Sistemeve Komplekse
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (161, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 10), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (161, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 11), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (161, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 12), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (161, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 13), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 162: Machine Learning
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (162, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 14), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (162, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 15), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (162, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 16), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (162, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 17), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 163: Computer Vision
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (163, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 18), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (163, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 19), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (163, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 20), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (163, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'DETYRE_KURSI', 0.0, 5.0);
