-- V50: Configure Semester, Duration Weeks and Teaching Courses breakdown for Inteligjence Artificiale dhe Optimizim Master - Year 2
-- Program: Inteligjencë Artificiale dhe Optimizim (Master Shkencor), Study Year: 2, Duration: 12 weeks

-- Step 1: Update SEMESTER and DURATION_WEEKS on COURSES table
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 164; -- Modelimi i Ngjarjeve të Pasigurta
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 165; -- Optimizim
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 166; -- Analizë të Dhënash dhe Statistikë e Avancuar
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 167; -- Deep Learning
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 168; -- Modelimi dhe Optimizimi i Sistemeve Diskrete
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 169; -- Teoria e Vendimit për Ngjarjet e Pasigurta
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 170; -- Optimizimi me Siguri të Lartë
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 171; -- Projekt Ndërdiciplinor
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 172; -- Inovacion dhe Start Up në TIK

UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 173; -- Praktikë
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 174; -- Diploma

-- Step 2: Clean up any dependent child tables referencing old TEACHING_COURSES for Year 2 AI
DELETE FROM FTIAPP.ATTENDANCE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174));
DELETE FROM FTIAPP.GRADES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174));
DELETE FROM FTIAPP.TOPICS WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174));
DELETE FROM FTIAPP.FAILED_COURSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174));
DELETE FROM FTIAPP.COURSE_SCHEDULE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174));
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174));
DELETE FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174);

-- Step 3: Insert Teaching Courses for Semestri 1
-- Course 164: Modelimi i Ngjarjeve të Pasigurta
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (164, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 1.5, 15.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (164, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (164, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 165: Optimizim
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (165, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'LEKSION', 2.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (165, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'SEMINAR', 0.5, 6.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (165, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 166: Analizë të Dhënash dhe Statistikë e Avancuar
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (166, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LEKSION', 2.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (166, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 8), 'SEMINAR', 1.0, 12.0);

-- Course 167: Deep Learning
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (167, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 9), 'LEKSION', 1.5, 15.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (167, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 10), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (167, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 11), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 168: Modelimi dhe Optimizimi i Sistemeve Diskrete
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (168, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 12), 'LEKSION', 1.5, 15.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (168, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 13), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (168, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 14), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 169: Teoria e Vendimit për Ngjarjet e Pasigurta
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (169, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 15), 'LEKSION', 1.5, 15.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (169, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 16), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (169, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 17), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 170: Optimizimi me Siguri të Lartë
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (170, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 18), 'LEKSION', 2.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (170, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 19), 'SEMINAR', 0.5, 6.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (170, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 20), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 171: Projekt Ndërdiciplinor
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (171, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 2.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (171, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'DETYRE_KURSI', 0.0, 20.0);

-- Course 172: Inovacion dhe Start Up në TIK
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (172, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LEKSION', 2.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (172, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'SEMINAR', 1.0, 12.0);

-- Step 4: Insert Teaching Courses for Semestri 2
-- Course 173: Praktikë
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (173, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'PRAKTIKE', 0.0, 240.0);

-- Course 174: Diploma
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (174, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'DIPLOME', 0.0, 90.0);
