-- V51: Configure Semester, Duration Weeks and Teaching Courses breakdown for Inxhinieri Informatike Master - Year 1
-- Program: Inxhinieri Informatike (Master Shkencor), Study Year: 1, Duration: 12 weeks

-- Step 1: Update SEMESTER and DURATION_WEEKS on COURSES table
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 137; -- Procese stokastike dhe Statistikë
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 138; -- Programim i avancuar
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 139; -- Inteligjenca Artificiale
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 140; -- Menaxhimi i projekteve
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 141; -- Cloud Computing

UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 142; -- Inxhinieri e software-it 2
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 143; -- Kërkime Operacionale
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 144; -- Machine Learning (Lëndë me zgjedhje 1)
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 145; -- Sisteme operative 2
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 146; -- Inxhinieria e Sistemeve Komplekse (Lëndë me zgjedhje 2)

-- Step 2: Clean up any dependent child tables referencing old TEACHING_COURSES for Year 1 Master Informatike
DELETE FROM FTIAPP.ATTENDANCE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (137, 138, 139, 140, 141, 142, 143, 144, 145, 146));
DELETE FROM FTIAPP.GRADES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (137, 138, 139, 140, 141, 142, 143, 144, 145, 146));
DELETE FROM FTIAPP.TOPICS WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (137, 138, 139, 140, 141, 142, 143, 144, 145, 146));
DELETE FROM FTIAPP.FAILED_COURSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (137, 138, 139, 140, 141, 142, 143, 144, 145, 146));
DELETE FROM FTIAPP.COURSE_SCHEDULE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (137, 138, 139, 140, 141, 142, 143, 144, 145, 146));
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (137, 138, 139, 140, 141, 142, 143, 144, 145, 146));
DELETE FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (137, 138, 139, 140, 141, 142, 143, 144, 145, 146);

-- Step 3: Insert Teaching Courses for Semestri 1
-- Course 137: Procese stokastike dhe Statistikë
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (137, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (137, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (137, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 138: Programim i avancuar
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (138, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'LEKSION', 4.0, 40.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (138, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'SEMINAR', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (138, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (138, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 139: Inteligjenca Artificiale
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (139, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 8), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (139, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 9), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (139, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 10), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (139, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 11), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 140: Menaxhimi i projekteve
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (140, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 12), 'LEKSION', 2.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (140, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 13), 'SEMINAR', 1.5, 18.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (140, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 14), 'DETYRE_KURSI', 0.0, 2.5);

-- Course 141: Cloud Computing
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (141, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 15), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (141, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 16), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (141, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 17), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (141, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 18), 'DETYRE_KURSI', 0.0, 5.0);

-- Step 4: Insert Teaching Courses for Semestri 2
-- Course 142: Inxhinieri e software-it 2
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (142, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 19), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (142, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 20), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (142, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (142, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 143: Kërkime Operacionale
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (143, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (143, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (143, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (143, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 144: Machine Learning (Lëndë me zgjedhje 1)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (144, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (144, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 8), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (144, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 9), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (144, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 10), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 145: Sisteme operative 2
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (145, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 11), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (145, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 12), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (145, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 13), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (145, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 14), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 146: Inxhinieria e Sistemeve Komplekse (Lëndë me zgjedhje 2)
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (146, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 15), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (146, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 16), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (146, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 17), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (146, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 18), 'DETYRE_KURSI', 0.0, 5.0);
