-- V52: Configure Semester, Duration Weeks and Teaching Courses breakdown for Inxhinieri Informatike Master - Year 2
-- Program: Inxhinieri Informatike (Master Shkencor), Study Year: 2, Duration: 12 weeks

-- Step 1: Update SEMESTER and DURATION_WEEKS on COURSES table
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 147; -- Big Data: Arkitektura edhe Analiza e të Dhënave
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 148; -- Teknologjitë e bazave të të dhënave
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 149; -- Arkitektura e sistemeve të përpunimit
UPDATE FTIAPP.COURSES SET SEMESTER = '1', DURATION_WEEKS = 12 WHERE COURSE_ID = 150; -- Rrjetat e kompjuterave 2

UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 151; -- Praktikë
UPDATE FTIAPP.COURSES SET SEMESTER = '2', DURATION_WEEKS = 12 WHERE COURSE_ID = 152; -- Diploma

-- Step 2: Clean up any dependent child tables referencing old TEACHING_COURSES for Year 2 Master Informatike
DELETE FROM FTIAPP.ATTENDANCE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (147, 148, 149, 150, 151, 152));
DELETE FROM FTIAPP.GRADES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (147, 148, 149, 150, 151, 152));
DELETE FROM FTIAPP.TOPICS WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (147, 148, 149, 150, 151, 152));
DELETE FROM FTIAPP.FAILED_COURSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (147, 148, 149, 150, 151, 152));
DELETE FROM FTIAPP.COURSE_SCHEDULE WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (147, 148, 149, 150, 151, 152));
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES WHERE TEACHING_COURSE_ID IN (SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (147, 148, 149, 150, 151, 152));
DELETE FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID IN (147, 148, 149, 150, 151, 152);

-- Step 3: Insert Teaching Courses for Semestri 1
-- Course 147: Big Data: Arkitektura edhe Analiza e të Dhënave
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (147, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 1), 'LEKSION', 3.0, 30.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (147, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 2), 'SEMINAR', 1.0, 12.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (147, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 3), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (147, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 4), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 148: Teknologjitë e bazave të të dhënave
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (148, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 5), 'LEKSION', 4.0, 40.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (148, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 6), 'SEMINAR', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (148, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 7), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (148, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 8), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 149: Arkitektura e sistemeve të përpunimit
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (149, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 9), 'LEKSION', 4.0, 40.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (149, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 10), 'SEMINAR', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (149, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 11), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (149, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 12), 'DETYRE_KURSI', 0.0, 5.0);

-- Course 150: Rrjetat e kompjuterave 2
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (150, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 13), 'LEKSION', 4.0, 40.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (150, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 14), 'SEMINAR', 2.0, 24.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (150, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 15), 'LABORATOR', 0.0, 20.0);
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (150, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 16), 'DETYRE_KURSI', 0.0, 5.0);

-- Step 4: Insert Teaching Courses for Semestri 2
-- Course 151: Praktikë
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (151, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 17), 'PRAKTIKE', 0.0, 240.0);

-- Course 152: Diploma
INSERT INTO FTIAPP.TEACHING_COURSES (COURSE_ID, PROFESSOR_ID, ROLE_TYPE, WEEKLY_HOURS, TOTAL_HOURS) 
VALUES (152, (SELECT PROFESSOR_ID FROM (SELECT PROFESSOR_ID, ROWNUM rn FROM FTIAPP.PROFESSORS ORDER BY PROFESSOR_ID) WHERE rn = 18), 'DIPLOME', 0.0, 90.0);
