ALTER TABLE FTIAPP.TEACHING_COURSES ADD (ACADEMIC_YEAR VARCHAR2(20) DEFAULT '2025-2026');
UPDATE FTIAPP.TEACHING_COURSES SET ACADEMIC_YEAR = '2025-2026' WHERE ACADEMIC_YEAR IS NULL;

ALTER TABLE FTIAPP.COURSE_SCHEDULE DROP COLUMN ACADEMIC_YEAR;
