-- V59: Caktojmë lëndën Algoritmikë (Viti 3) për Altea Kostallari me grupet përkatëse:
-- Leksion: Të gjitha grupet
-- Seminar: Grupi A dhe Grupi B
-- Laborator: Grupi A dhe Grupi B
-- Detyrë Kursi: Grupi A dhe Grupi C

-- 1. Përditësojmë pedagogun e TEACHING_COURSES për lëndën Algoritmikë tek Altea Kostallari
UPDATE FTIAPP.TEACHING_COURSES tc
SET tc.PROFESSOR_ID = (
    SELECT p.PROFESSOR_ID 
    FROM FTIAPP.PROFESSORS p
    LEFT JOIN FTIAPP.USERS u ON p.USER_ID = u.USER_ID
    WHERE LOWER(u.EMAIL) LIKE '%altea%' OR LOWER(u.EMRI) LIKE '%altea%' OR p.PROFESSOR_ID = 26
    FETCH FIRST 1 ROWS ONLY
)
WHERE tc.COURSE_ID IN (
    SELECT c.COURSE_ID FROM FTIAPP.COURSES c
    WHERE (LOWER(c.EMRI_COURSE) LIKE '%algoritm%' OR c.COURSE_ID = 26)
      AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
);

-- 2. Pastrojmë lidhjet ekzistuese në TEACHING_COURSES_CLASSES për këtë lëndë
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES 
WHERE TEACHING_COURSE_ID IN (
    SELECT tc.TEACHING_COURSE_ID 
    FROM FTIAPP.TEACHING_COURSES tc
    JOIN FTIAPP.COURSES c ON tc.COURSE_ID = c.COURSE_ID
    WHERE (LOWER(c.EMRI_COURSE) LIKE '%algoritm%' OR c.COURSE_ID = 26)
      AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
);

-- 3. Lidhja e Leksionit me të gjitha grupet e Vitit 3
INSERT INTO FTIAPP.TEACHING_COURSES_CLASSES (TEACHING_COURSE_ID, CLASS_ID)
SELECT DISTINCT tc.TEACHING_COURSE_ID, cl.CLASS_ID
FROM FTIAPP.TEACHING_COURSES tc
JOIN FTIAPP.COURSES c ON tc.COURSE_ID = c.COURSE_ID
JOIN FTIAPP.CLASSES cl ON cl.PROGRAM_ID = c.PROGRAM_ID AND (cl.VIT_STUDIMIT = c.STUDY_YEAR OR c.STUDY_YEAR IS NULL)
WHERE (LOWER(c.EMRI_COURSE) LIKE '%algoritm%' OR c.COURSE_ID = 26)
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND UPPER(tc.ROLE_TYPE) = 'LEKSION';

-- 4. Lidhja e Seminarit me Grupin A dhe Grupin B
INSERT INTO FTIAPP.TEACHING_COURSES_CLASSES (TEACHING_COURSE_ID, CLASS_ID)
SELECT DISTINCT tc.TEACHING_COURSE_ID, cl.CLASS_ID
FROM FTIAPP.TEACHING_COURSES tc
JOIN FTIAPP.COURSES c ON tc.COURSE_ID = c.COURSE_ID
JOIN FTIAPP.CLASSES cl ON cl.PROGRAM_ID = c.PROGRAM_ID AND (cl.VIT_STUDIMIT = c.STUDY_YEAR OR c.STUDY_YEAR IS NULL)
WHERE (LOWER(c.EMRI_COURSE) LIKE '%algoritm%' OR c.COURSE_ID = 26)
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND UPPER(tc.ROLE_TYPE) = 'SEMINAR'
  AND (UPPER(cl.EMRI_CLASS) LIKE '%A%' OR UPPER(cl.EMRI_CLASS) LIKE '%B%');

-- 5. Lidhja e Laboratorit me Grupin A dhe Grupin B
INSERT INTO FTIAPP.TEACHING_COURSES_CLASSES (TEACHING_COURSE_ID, CLASS_ID)
SELECT DISTINCT tc.TEACHING_COURSE_ID, cl.CLASS_ID
FROM FTIAPP.TEACHING_COURSES tc
JOIN FTIAPP.COURSES c ON tc.COURSE_ID = c.COURSE_ID
JOIN FTIAPP.CLASSES cl ON cl.PROGRAM_ID = c.PROGRAM_ID AND (cl.VIT_STUDIMIT = c.STUDY_YEAR OR c.STUDY_YEAR IS NULL)
WHERE (LOWER(c.EMRI_COURSE) LIKE '%algoritm%' OR c.COURSE_ID = 26)
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND UPPER(tc.ROLE_TYPE) = 'LABORATOR'
  AND (UPPER(cl.EMRI_CLASS) LIKE '%A%' OR UPPER(cl.EMRI_CLASS) LIKE '%B%');

-- 6. Lidhja e Detyrës së Kursit me Grupin A dhe Grupin C
INSERT INTO FTIAPP.TEACHING_COURSES_CLASSES (TEACHING_COURSE_ID, CLASS_ID)
SELECT DISTINCT tc.TEACHING_COURSE_ID, cl.CLASS_ID
FROM FTIAPP.TEACHING_COURSES tc
JOIN FTIAPP.COURSES c ON tc.COURSE_ID = c.COURSE_ID
JOIN FTIAPP.CLASSES cl ON cl.PROGRAM_ID = c.PROGRAM_ID AND (cl.VIT_STUDIMIT = c.STUDY_YEAR OR c.STUDY_YEAR IS NULL)
WHERE (LOWER(c.EMRI_COURSE) LIKE '%algoritm%' OR c.COURSE_ID = 26)
  AND (c.STUDY_YEAR = 3 OR c.STUDY_YEAR IS NULL)
  AND (UPPER(tc.ROLE_TYPE) LIKE '%DETYR%' OR UPPER(tc.ROLE_TYPE) = 'DETYRE_KURSI')
  AND (UPPER(cl.EMRI_CLASS) LIKE '%A%' OR UPPER(cl.EMRI_CLASS) LIKE '%C%');
