CREATE TABLE FTIAPP.PROFESSOR_PRE_ENROLLMENT (
    PRE_ENROLLMENT_ID INTEGER NOT NULL,
    EMRI              VARCHAR2(50) NOT NULL,
    MBIEMRI           VARCHAR2(50) NOT NULL,
    EMAIL             VARCHAR2(100) NOT NULL,
    DEPARTMENT_ID     INTEGER NOT NULL,
    CONSTRAINT PK_PROFESSOR_PRE_ENROLLMENT PRIMARY KEY (PRE_ENROLLMENT_ID),
    CONSTRAINT UQ_PROF_PRE_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_PROF_PRE_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES FTIAPP.DEPARTMENTS(DEPARTMENT_ID)
);

CREATE SEQUENCE FTIAPP.SEQ_PROF_PRE_ENROLLMENT START WITH 1 INCREMENT BY 1 NOCACHE;
