-- Clean up any other academic years so only 2025-2026 exists and is active
DELETE FROM ACADEMIC_YEAR WHERE YEAR_LABEL != '2025-2026';
UPDATE ACADEMIC_YEAR SET IS_ACTIVE = 1 WHERE YEAR_LABEL = '2025-2026';

-- Link all existing teaching courses and exam seasons to 2025-2026
UPDATE FTIAPP.TEACHING_COURSES SET ACADEMIC_YEAR = '2025-2026';
UPDATE FTIAPP.EXAM_SEASONS SET ACADEMIC_YEAR = '2025-2026' WHERE ACADEMIC_YEAR IS NOT NULL;

-- Add Foreign Key constraint from TEACHING_COURSES to ACADEMIC_YEAR
ALTER TABLE FTIAPP.TEACHING_COURSES
    ADD CONSTRAINT FK_TC_ACADEMIC_YEAR
    FOREIGN KEY (ACADEMIC_YEAR)
    REFERENCES ACADEMIC_YEAR(YEAR_LABEL);

-- Add Foreign Key constraint from EXAM_SEASONS to ACADEMIC_YEAR
ALTER TABLE FTIAPP.EXAM_SEASONS
    ADD CONSTRAINT FK_EXAM_SEASONS_ACAD_YEAR
    FOREIGN KEY (ACADEMIC_YEAR)
    REFERENCES ACADEMIC_YEAR(YEAR_LABEL);
