-- V63: Kalojmë Analizën Matematike 1 të Altea Kostallarit ekskluzivisht tek Inxhinieri Informatike (Course 4)
-- dhe ia heqim Inxhinierinë Kompjuterike (Course 106)

-- 1. Caktojmë seminarin e Kursit 4 (Inxhinieri Informatike) tek Altea Kostallari
UPDATE FTIAPP.TEACHING_COURSES
SET PROFESSOR_ID = (
    SELECT p.PROFESSOR_ID 
    FROM FTIAPP.PROFESSORS p
    LEFT JOIN FTIAPP.USERS u ON p.USER_ID = u.USER_ID
    WHERE LOWER(u.EMAIL) LIKE '%altea%' OR LOWER(u.EMRI) LIKE '%altea%' OR p.PROFESSOR_ID = 3
    FETCH FIRST 1 ROWS ONLY
)
WHERE COURSE_ID = 4 AND UPPER(ROLE_TYPE) = 'SEMINAR';

-- 2. Caktojmë seminarin e Kursit 106 (Inxhinieri Kompjuterike) tek një pedagog tjetër (Hakik Paci ose profId=61)
UPDATE FTIAPP.TEACHING_COURSES
SET PROFESSOR_ID = NVL((
    SELECT p.PROFESSOR_ID 
    FROM FTIAPP.PROFESSORS p
    LEFT JOIN FTIAPP.USERS u ON p.USER_ID = u.USER_ID
    WHERE LOWER(u.EMRI) LIKE '%hakik%' OR p.PROFESSOR_ID = 61
    FETCH FIRST 1 ROWS ONLY
), 61)
WHERE COURSE_ID = 106 AND UPPER(ROLE_TYPE) = 'SEMINAR';

-- 3. Sigurojmë lidhjet e klasave të Kursit 4 për Seminar tek Grupet A dhe B të Vitit 1 Informatikë
DELETE FROM FTIAPP.TEACHING_COURSES_CLASSES 
WHERE TEACHING_COURSE_ID IN (
    SELECT TEACHING_COURSE_ID FROM FTIAPP.TEACHING_COURSES WHERE COURSE_ID = 4 AND UPPER(ROLE_TYPE) = 'SEMINAR'
);

INSERT INTO FTIAPP.TEACHING_COURSES_CLASSES (TEACHING_COURSE_ID, CLASS_ID)
SELECT tc.TEACHING_COURSE_ID, cl.CLASS_ID
FROM FTIAPP.TEACHING_COURSES tc
JOIN FTIAPP.CLASSES cl ON cl.PROGRAM_ID = (SELECT PROGRAM_ID FROM FTIAPP.COURSES WHERE COURSE_ID = 4)
                      AND cl.VIT_STUDIMIT = 1
WHERE tc.COURSE_ID = 4 
  AND UPPER(tc.ROLE_TYPE) = 'SEMINAR'
  AND (UPPER(cl.EMRI_CLASS) LIKE '%A%' OR UPPER(cl.EMRI_CLASS) LIKE '%B%');
